kind: pipeline
type: docker
name: "Deploy to production"

steps:
  - name: build
    image: plugins/docker
    settings:
      registry: http://container-registry:5000
      repo: container-registry:5000/${DRONE_REPO,,}
      auto_tag: false
      insecure: true
      dockerfile: ./Dockerfile
      tags: prod
    when:
      branch:
        - master
