# Generated by Django 3.2.6 on 2022-02-15 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='type')),
            ],
            options={
                'verbose_name': 'CareerCategory',
                'verbose_name_plural': 'CareerCategories',
            },
        ),
        migrations.CreateModel(
            name='CoFounder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('full_name_en', models.CharField(max_length=100, null=True, verbose_name='full name')),
                ('full_name_ru', models.CharField(max_length=100, null=True, verbose_name='full name')),
                ('full_name_tr', models.CharField(max_length=100, null=True, verbose_name='full name')),
                ('img', models.ImageField(upload_to='cofounders/')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('desc_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('desc_ru', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('desc_tr', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'CoFounder',
                'verbose_name_plural': 'CoFounders',
            },
        ),
        migrations.CreateModel(
            name='NewsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100, verbose_name='type')),
                ('type_en', models.CharField(max_length=100, null=True, verbose_name='type')),
                ('type_ru', models.CharField(max_length=100, null=True, verbose_name='type')),
                ('type_tr', models.CharField(max_length=100, null=True, verbose_name='type')),
                ('bg_color', models.CharField(max_length=100, verbose_name='background color')),
            ],
            options={
                'verbose_name': 'NewsCategory',
                'verbose_name_plural': 'NewsCategories',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('title_en', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('title_tr', models.CharField(max_length=100, null=True, verbose_name='title')),
                ('cover_img', models.ImageField(upload_to='projects/')),
                ('desc', models.TextField(verbose_name='Description')),
                ('desc_en', models.TextField(null=True, verbose_name='Description')),
                ('desc_ru', models.TextField(null=True, verbose_name='Description')),
                ('desc_tr', models.TextField(null=True, verbose_name='Description')),
                ('detail_img', models.ImageField(upload_to='projects/')),
                ('text', models.TextField(verbose_name='Text')),
                ('text_en', models.TextField(null=True, verbose_name='Text')),
                ('text_ru', models.TextField(null=True, verbose_name='Text')),
                ('text_tr', models.TextField(null=True, verbose_name='Text')),
                ('link', models.URLField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
            },
        ),
        migrations.CreateModel(
            name='ShareHolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='full name')),
                ('full_name_en', models.CharField(max_length=100, null=True, verbose_name='full name')),
                ('full_name_ru', models.CharField(max_length=100, null=True, verbose_name='full name')),
                ('full_name_tr', models.CharField(max_length=100, null=True, verbose_name='full name')),
                ('img', models.ImageField(upload_to='cofounders/')),
                ('desc', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('desc_en', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('desc_ru', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('desc_tr', models.TextField(blank=True, null=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'ShareHolder',
                'verbose_name_plural': 'ShareHolders',
            },
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_tr', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('cover_img', models.ImageField(upload_to='news/')),
                ('desc', models.TextField()),
                ('desc_en', models.TextField(null=True)),
                ('desc_ru', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('img1', models.ImageField(upload_to='news/')),
                ('img2', models.ImageField(upload_to='news/')),
                ('img3', models.ImageField(upload_to='news/')),
                ('img4', models.ImageField(upload_to='news/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.newscategory')),
            ],
            options={
                'verbose_name': 'News',
                'verbose_name_plural': 'News',
            },
        ),
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('ln_link', models.URLField(max_length=255)),
                ('comment', models.TextField()),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.careercategory')),
            ],
            options={
                'verbose_name': 'Career',
                'verbose_name_plural': 'Careers',
            },
        ),
    ]
