# Generated by Django 3.2.6 on 2021-12-22 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cofounder',
            name='desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='cofounder',
            name='desc_rus',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='cofounder',
            name='desc_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='cofounder',
            name='full_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='cofounder',
            name='full_name_rus',
            field=models.CharField(max_length=100, null=True, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='cofounder',
            name='full_name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='news',
            name='desc_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='desc_rus',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='desc_tr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_rus',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_tr',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='type_en',
            field=models.CharField(max_length=100, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='type_rus',
            field=models.CharField(max_length=100, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='newscategory',
            name='type_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='type'),
        ),
        migrations.AddField(
            model_name='project',
            name='desc_en',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='desc_rus',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='desc_tr',
            field=models.TextField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='project',
            name='text_en',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='project',
            name='text_rus',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='project',
            name='text_tr',
            field=models.TextField(null=True, verbose_name='Text'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_en',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_rus',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='project',
            name='title_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='desc_en',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='desc_rus',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='desc_tr',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='full_name_en',
            field=models.CharField(max_length=100, null=True, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='full_name_rus',
            field=models.CharField(max_length=100, null=True, verbose_name='full name'),
        ),
        migrations.AddField(
            model_name='shareholder',
            name='full_name_tr',
            field=models.CharField(max_length=100, null=True, verbose_name='full name'),
        ),
    ]
