# Generated by Django 3.2.6 on 2022-02-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220215_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllocationFund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_tr', models.CharField(max_length=255, null=True, verbose_name='title')),
            ],
            options={
                'verbose_name': 'AllocationFund',
                'verbose_name_plural': 'AllocationFunds',
            },
        ),
        migrations.CreateModel(
            name='Coin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('title_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('img', models.ImageField(blank=True, null=True, upload_to='coins/')),
                ('desc', models.TextField()),
                ('desc_en', models.TextField(null=True)),
                ('desc_ru', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('ln_link', models.URLField(max_length=255)),
            ],
            options={
                'verbose_name': 'Coin',
                'verbose_name_plural': 'Coins',
            },
        ),
        migrations.CreateModel(
            name='CoinDeadline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deadline', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'CoinDeadline',
                'verbose_name_plural': 'CoinDeadlines',
            },
        ),
        migrations.CreateModel(
            name='CoinFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature', models.CharField(max_length=255, verbose_name='feature')),
                ('feature_en', models.CharField(max_length=255, null=True, verbose_name='feature')),
                ('feature_ru', models.CharField(max_length=255, null=True, verbose_name='feature')),
                ('feature_tr', models.CharField(max_length=255, null=True, verbose_name='feature')),
                ('count', models.IntegerField(verbose_name='count')),
            ],
            options={
                'verbose_name': 'CoinFeature',
                'verbose_name_plural': 'CoinFeatures',
            },
        ),
        migrations.CreateModel(
            name='CoinField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('title_tr', models.CharField(blank=True, max_length=255, null=True, verbose_name='title')),
                ('img', models.ImageField(blank=True, null=True, upload_to='coins/')),
                ('desc', models.TextField()),
                ('desc_en', models.TextField(null=True)),
                ('desc_ru', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'CoinField',
                'verbose_name_plural': 'CoinFields',
            },
        ),
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_tr', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('desc', models.TextField()),
                ('desc_en', models.TextField(null=True)),
                ('desc_ru', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'TimeLine',
                'verbose_name_plural': 'TimeLines',
            },
        ),
    ]
