# Generated by Django 3.2.6 on 2022-02-18 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_allocationfund_coin_coindeadline_coinfeature_coinfield_timeline'),
        ('api', '0003_auto_20211222_1906'),
    ]

    operations = [
    ]
