# Generated by Django 3.2.6 on 2022-04-11 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_allocationfund_coin_coindeadline_coinfeature_coinfield_timeline'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_ru', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('title_tr', models.CharField(max_length=255, null=True, verbose_name='title')),
                ('logo', models.ImageField(upload_to='partners/')),
                ('cover_img', models.ImageField(upload_to='partners/')),
                ('short_desc', models.TextField()),
                ('short_desc_en', models.TextField(null=True)),
                ('short_desc_ru', models.TextField(null=True)),
                ('short_desc_tr', models.TextField(null=True)),
                ('desc', models.TextField()),
                ('desc_en', models.TextField(null=True)),
                ('desc_ru', models.TextField(null=True)),
                ('desc_tr', models.TextField(null=True)),
                ('img1', models.ImageField(blank=True, null=True, upload_to='news/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Partner',
                'verbose_name_plural': 'Partners',
            },
        ),
    ]
