# Generated by Django 3.2.6 on 2022-05-11 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareholder',
            name='sequence',
            field=models.IntegerField(default=0),
        ),
    ]
