# Generated by Django 3.2.6 on 2022-05-14 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20220512_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeline',
            name='increment',
            field=models.IntegerField(default=0),
        ),
    ]
