# Generated by Django 3.2.6 on 2022-05-24 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_clothingslider_clothingsliderimage_companyslider_companysliderimage_creativeslide_creativesliderimag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sliders/', verbose_name='Enter img url')),
            ],
            options={
                'verbose_name': 'SliderImage',
                'verbose_name_plural': 'SliderImages',
            },
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='sliders/')),
                ('img', models.ManyToManyField(to='api.SliderImage')),
            ],
            options={
                'verbose_name': 'lider',
                'verbose_name_plural': 'Sliders',
            },
        ),
    ]
