# Generated by Django 3.2.6 on 2022-05-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_slider_sliderimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='id_number',
            field=models.IntegerField(default=0),
        ),
    ]
